app: vjepa
nodes: 1
tasks_per_node: 8
cpus_per_task: 8
mem_per_gpu: 80G
folder: /data/chainflow-vla/outputs/vjepa2/vjepa2-fpc4-camf0-256x512-vitg-navsim-50wclip-test
data:
  dataset_type: VideoDataset
  datasets:
  - /data/chainflow-vla/navsim_vjepa_fpc4_camf0/train.csv
  datasets_weights:
  - 1.0
  batch_size: 64
  crop_size: [256, 512]
  dataset_fpcs:
  - 4
  fps: 2
  num_workers: 4
  patch_size: 16
  persistent_workers: true
  pin_mem: true
  tubelet_size: 2
data_aug:
  auto_augment: false
  motion_shift: false
  random_horizontal_flip: false
  random_resize_aspect_ratio:
  - 2.0
  - 2.0
  random_resize_scale:
  - 1.0
  - 1.0
  reprob: 0.0
loss:
  loss_exp: 1.0
mask:
- aspect_ratio:
  - 0.75
  - 1.5
  full_complement: false
  max_keep: null
  max_temporal_keep: 1.0
  num_blocks: 8
  spatial_scale:
  - 0.15
  - 0.15
  temporal_scale:
  - 1.0
  - 1.0
- aspect_ratio:
  - 0.75
  - 1.5
  full_complement: false
  max_keep: null
  max_temporal_keep: 1.0
  num_blocks: 2
  spatial_scale:
  - 0.7
  - 0.7
  temporal_scale:
  - 1.0
  - 1.0
meta:
  dtype: bfloat16
  eval_freq: 100
  load_checkpoint: true
  read_checkpoint: null
  save_every_freq: 10
  seed: 239
  use_sdpa: true
model:
  model_name: vit_giant_xformers
  pred_depth: 12
  pred_embed_dim: 384
  pred_num_heads: 12
  uniform_power: true
  use_activation_checkpointing: true
  use_mask_tokens: true
  use_rope: true
  zero_init_mask_tokens: true
optimization:
  anneal_ckpt: /data/e2e/diffusiondrive/vjepa2/ckpts/vjepa2-vitg-fpc64-256/original/model.pth
  ema:
  - 0.99925
  - 0.99925
  epochs: 50
  final_lr: 0.000525
  final_weight_decay: 0.04
  ipe: 300
  ipe_scale: 1.25
  is_anneal: true
  resume_anneal: true
  lr: 0.0006
  start_lr: 0.0001
  warmup: 0
  weight_decay: 0.04
